import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "./components/Smoothscroller";
import localFont from 'next/font/local'
import { SmoothCursor } from "@/components/ui/smooth-cursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const myfont = localFont({
  src: '../public/fonts/Compacta Bold.otf',
  weight: '400',
  style: 'normal',
  variable: '--font-myfont',
});

const benzin = localFont({
  src: '../public/fonts/benzin-semibold.ttf',
  weight: '400',
  style: 'normal',
  variable: '--font-benzin',
});

export const metadata: Metadata = {
  title: "Raswanth's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`dark ${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${myfont.variable} ${benzin.variable} antialiased` }
      >
          <SmoothScrolling>
        {children}
        <SmoothCursor />
        </SmoothScrolling>
      </body>
    </html>
  );
}
